<a href="https://colab.research.google.com/github/MontserratMartinezLopez/Algebra-Lineal/blob/main/Tarea_5_(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Librerias

In [2]:
!pip install --target=$nb_path nacal
from nacal import *

##Ejercicio 1

1. Para la siguiente matriz $$\left[ \begin{array}{cccc}3&-2&2&1\\1&-1&-1&-3\\2&1&2&4\\4&-4&1&2\\ \end{array} \right]$$ lleva a cabo el algoritmo de eliminación paso a paso.

Escribe en una celda separada cada operacion elemental.

In [3]:
w= Vector((3,1,1,4)); x=Vector((-2,-1,1,-4)); y= Vector((2,-1,2,1)); z= Vector((1,-3,4,2))
M= Matrix([w,x,y,z])
M

$\left[ \begin{array}{cccc}3&-2&2&1\\1&-1&-1&-3\\1&1&2&4\\4&-4&1&2\\ \end{array} \right]$

In [4]:
M&T((fracc(1,3),1))

$\left[ \begin{array}{cccc}1&-2&2&1\\\frac{1}{3}&-1&-1&-3\\\frac{1}{3}&1&2&4\\\frac{4}{3}&-4&1&2\\ \end{array} \right]$

In [5]:
M&T((2,1,2))

$\left[ \begin{array}{cccc}1&0&2&1\\\frac{1}{3}&- \frac{1}{3}&-1&-3\\\frac{1}{3}&\frac{5}{3}&2&4\\\frac{4}{3}&- \frac{4}{3}&1&2\\ \end{array} \right]$

In [6]:
M&T((-2,1,3))

$\left[ \begin{array}{cccc}1&0&0&1\\\frac{1}{3}&- \frac{1}{3}&- \frac{5}{3}&-3\\\frac{1}{3}&\frac{5}{3}&\frac{4}{3}&4\\\frac{4}{3}&- \frac{4}{3}&- \frac{5}{3}&2\\ \end{array} \right]$

In [7]:
M&T((-1,1,4))

$\left[ \begin{array}{cccc}1&0&0&0\\\frac{1}{3}&- \frac{1}{3}&- \frac{5}{3}&- \frac{10}{3}\\\frac{1}{3}&\frac{5}{3}&\frac{4}{3}&\frac{11}{3}\\\frac{4}{3}&- \frac{4}{3}&- \frac{5}{3}&\frac{2}{3}\\ \end{array} \right]$

In [8]:
M&T((-fracc(3,1),2))

$\left[ \begin{array}{cccc}1&0&0&0\\\frac{1}{3}&1&- \frac{5}{3}&- \frac{10}{3}\\\frac{1}{3}&-5&\frac{4}{3}&\frac{11}{3}\\\frac{4}{3}&4&- \frac{5}{3}&\frac{2}{3}\\ \end{array} \right]$

In [9]:
M&T((-fracc(1,3),2,1))

$\left[ \begin{array}{cccc}1&0&0&0\\0&1&- \frac{5}{3}&- \frac{10}{3}\\2&-5&\frac{4}{3}&\frac{11}{3}\\0&4&- \frac{5}{3}&\frac{2}{3}\\ \end{array} \right]$

In [10]:
M&T((fracc(5,3),2,3))

$\left[ \begin{array}{cccc}1&0&0&0\\0&1&0&- \frac{10}{3}\\2&-5&-7&\frac{11}{3}\\0&4&5&\frac{2}{3}\\ \end{array} \right]$

In [11]:
M&T((fracc(10,3),2,4))

$\left[ \begin{array}{cccc}1&0&0&0\\0&1&0&0\\2&-5&-7&-13\\0&4&5&14\\ \end{array} \right]$

In [12]:
M&T((-fracc(1,7),3))

$\left[ \begin{array}{cccc}1&0&0&0\\0&1&0&0\\2&-5&1&-13\\0&4&- \frac{5}{7}&14\\ \end{array} \right]$

In [13]:
M&T((-2,3,1))

$\left[ \begin{array}{cccc}1&0&0&0\\0&1&0&0\\0&-5&1&-13\\\frac{10}{7}&4&- \frac{5}{7}&14\\ \end{array} \right]$

In [14]:
M&T((5,3,2))

$\left[ \begin{array}{cccc}1&0&0&0\\0&1&0&0\\0&0&1&-13\\\frac{10}{7}&\frac{3}{7}&- \frac{5}{7}&14\\ \end{array} \right]$

In [15]:
M&T((13,3,4))

$\left[ \begin{array}{cccc}1&0&0&0\\0&1&0&0\\0&0&1&0\\\frac{10}{7}&\frac{3}{7}&- \frac{5}{7}&\frac{33}{7}\\ \end{array} \right]$

In [16]:
M&T((fracc(7,33),4))

$\left[ \begin{array}{cccc}1&0&0&0\\0&1&0&0\\0&0&1&0\\\frac{10}{7}&\frac{3}{7}&- \frac{5}{7}&1\\ \end{array} \right]$

In [17]:
M&T((-fracc(10,7),4,1))

$\left[ \begin{array}{cccc}1&0&0&0\\0&1&0&0\\0&0&1&0\\0&\frac{3}{7}&- \frac{5}{7}&1\\ \end{array} \right]$

In [18]:
M&T((-fracc(3,7),4,2))

$\left[ \begin{array}{cccc}1&0&0&0\\0&1&0&0\\0&0&1&0\\0&0&- \frac{5}{7}&1\\ \end{array} \right]$

In [19]:
M&T((fracc(5,7),4,3))

$\left[ \begin{array}{cccc}1&0&0&0\\0&1&0&0\\0&0&1&0\\0&0&0&1\\ \end{array} \right]$

##Ejercicio 2

2. Escriba las siguientes matrices elementales de orden 4.


(a) I τ
[(−7)1+3]

(b) I τ
[(1)1+4]

(c) I τ
[(3)2+1]

(d) I τ
[(−10)3]

In [20]:
I(4) & T( (-7,1,3) )

$\left[ \begin{array}{cccc}1&0&-7&0\\0&1&0&0\\0&0&1&0\\0&0&0&1\\ \end{array} \right]$

In [21]:
I(4) & T( (1,1,4) )

$\left[ \begin{array}{cccc}1&0&0&1\\0&1&0&0\\0&0&1&0\\0&0&0&1\\ \end{array} \right]$

In [22]:
I(4) & T( (3,2,1) )

$\left[ \begin{array}{cccc}1&0&0&0\\3&1&0&0\\0&0&1&0\\0&0&0&1\\ \end{array} \right]$

In [23]:
I(4) & T( (-10,3) )

$\left[ \begin{array}{cccc}1&0&0&0\\0&1&0&0\\0&0&-10&0\\0&0&0&1\\ \end{array} \right]$

##Ejercicio 3

3. Sea la matriz A = $\left[ \begin{array}{cccc}1&1&1&1\\0&1&1&1\\1&2&3&4\\4&-4&1&2\\ \end{array} \right]$
, exprese las siguientes transformaciones elementales de

A como productos de A por matrices elementales y escriba el resultado:

(a) Multiplicar la primera columna por 3. (b) Restar la primera columna de la segunda.

In [ ]:
w= Vector((1,0,1,4)); x=Vector((1,1,2,-4)); y= Vector((1,1,3,1)); z= Vector((1,1,4,2))
A= Matrix([w,x,y,z])
A

$\left[ \begin{array}{cccc}1&1&1&1\\0&1&1&1\\1&2&3&4\\4&-4&1&2\\ \end{array} \right]$

In [ ]:
A=A * ( I(A.n) &  T((3,1)) )
A

$\left[ \begin{array}{cccc}3&1&1&1\\0&1&1&1\\3&2&3&4\\12&-4&1&2\\ \end{array} \right]$

In [ ]:
A=A * ( I(A.n) &  T((-1,1,2)) )
A

$\left[ \begin{array}{cccc}3&-2&1&1\\0&1&1&1\\3&-1&3&4\\12&-16&1&2\\ \end{array} \right]$

##Ejercicio 4

4. Realiza el algoritmo de eliminación de Gauss-Jordan para la matriz del ejercicio 1, es decir continua las modificaciones de la matriz mediante operaciones elementales.
Por cada paso del algoritmo escribe la celda de código correspondiente.

In [ ]:
w= Vector((3,1,1,4)); x=Vector((-2,-1,1,-4)); y= Vector((2,-1,2,1)); z= Vector((1,-3,4,2))
N= Matrix([w,x,y,z])
N

$\left[ \begin{array}{cccc}3&-2&2&1\\1&-1&-1&-3\\1&1&2&4\\4&-4&1&2\\ \end{array} \right]$

In [ ]:
N&T((3,2))

$\left[ \begin{array}{cccc}3&-6&2&1\\1&-3&-1&-3\\1&3&2&4\\4&-12&1&2\\ \end{array} \right]$

In [ ]:
N&T((2,1,2))

$\left[ \begin{array}{cccc}3&0&2&1\\1&-1&-1&-3\\1&5&2&4\\4&-4&1&2\\ \end{array} \right]$

In [ ]:
N&T((3,3))

$\left[ \begin{array}{cccc}3&0&6&1\\1&-1&-3&-3\\1&5&6&4\\4&-4&3&2\\ \end{array} \right]$

In [ ]:
N&T((-2,1,3))

$\left[ \begin{array}{cccc}3&0&0&1\\1&-1&-5&-3\\1&5&4&4\\4&-4&-5&2\\ \end{array} \right]$

In [ ]:
N&T((3,4))

$\left[ \begin{array}{cccc}3&0&0&3\\1&-1&-5&-9\\1&5&4&12\\4&-4&-5&6\\ \end{array} \right]$

In [ ]:
N&T((-1,1,4))

$\left[ \begin{array}{cccc}3&0&0&0\\1&-1&-5&-10\\1&5&4&11\\4&-4&-5&2\\ \end{array} \right]$

In [ ]:
N&T((1,2,1))

$\left[ \begin{array}{cccc}3&0&0&0\\0&-1&-5&-10\\6&5&4&11\\0&-4&-5&2\\ \end{array} \right]$

In [ ]:
N&T((-5,2,3))

$\left[ \begin{array}{cccc}3&0&0&0\\0&-1&0&-10\\6&5&-21&11\\0&-4&15&2\\ \end{array} \right]$

In [ ]:
N&T((-10,2,4))

$\left[ \begin{array}{cccc}3&0&0&0\\0&-1&0&0\\6&5&-21&-39\\0&-4&15&42\\ \end{array} \right]$

In [ ]:
N&T((7,1))

$\left[ \begin{array}{cccc}21&0&0&0\\0&-1&0&0\\42&5&-21&-39\\0&-4&15&42\\ \end{array} \right]$

In [ ]:
N&T((2,3,1))

$\left[ \begin{array}{cccc}21&0&0&0\\0&-1&0&0\\0&5&-21&-39\\30&-4&15&42\\ \end{array} \right]$

In [ ]:
N&T((21,2))

$\left[ \begin{array}{cccc}21&0&0&0\\0&-21&0&0\\0&105&-21&-39\\30&-84&15&42\\ \end{array} \right]$

In [ ]:
N&T((5,3,2))

$\left[ \begin{array}{cccc}21&0&0&0\\0&-21&0&0\\0&0&-21&-39\\30&-9&15&42\\ \end{array} \right]$

In [ ]:
N&T((7,4))

$\left[ \begin{array}{cccc}21&0&0&0\\0&-21&0&0\\0&0&-21&-273\\30&-9&15&294\\ \end{array} \right]$

In [ ]:
N&T((-13,3,4))

$\left[ \begin{array}{cccc}21&0&0&0\\0&-21&0&0\\0&0&-21&0\\30&-9&15&99\\ \end{array} \right]$

In [ ]:
N&T((33,1))

$\left[ \begin{array}{cccc}693&0&0&0\\0&-21&0&0\\0&0&-21&0\\990&-9&15&99\\ \end{array} \right]$

In [ ]:
N&T((-10,4,1))

$\left[ \begin{array}{cccc}693&0&0&0\\0&-21&0&0\\0&0&-21&0\\0&-9&15&99\\ \end{array} \right]$

In [ ]:
N&T((11,2))

$\left[ \begin{array}{cccc}693&0&0&0\\0&-231&0&0\\0&0&-21&0\\0&-99&15&99\\ \end{array} \right]$

In [ ]:
N&T((1,4,2))

$\left[ \begin{array}{cccc}693&0&0&0\\0&-231&0&0\\0&0&-21&0\\0&0&15&99\\ \end{array} \right]$

In [ ]:
N&T((33,3))

$\left[ \begin{array}{cccc}693&0&0&0\\0&-231&0&0\\0&0&-693&0\\0&0&495&99\\ \end{array} \right]$

In [ ]:
N&T((-5,4,3))

$\left[ \begin{array}{cccc}693&0&0&0\\0&-231&0&0\\0&0&-693&0\\0&0&0&99\\ \end{array} \right]$

In [ ]:
N&T((fracc(1,693),1))

$\left[ \begin{array}{cccc}1&0&0&0\\0&-231&0&0\\0&0&-693&0\\0&0&0&99\\ \end{array} \right]$

In [ ]:
N&T((-fracc(1,231),2))

$\left[ \begin{array}{cccc}1&0&0&0\\0&1&0&0\\0&0&-693&0\\0&0&0&99\\ \end{array} \right]$

In [ ]:
N&T((-fracc(1,693),3))

$\left[ \begin{array}{cccc}1&0&0&0\\0&1&0&0\\0&0&1&0\\0&0&0&99\\ \end{array} \right]$

In [ ]:
N&T((fracc(1,99),4))

$\left[ \begin{array}{cccc}1&0&0&0\\0&1&0&0\\0&0&1&0\\0&0&0&1\\ \end{array} \right]$

##Ejercicio 5

5. Compara tus resultados del ejercicio 1 con el metodo Elim()

In [ ]:
w= Vector((3,1,1,4)); x=Vector((-2,-1,1,-4)); y= Vector((2,-1,2,1)); z= Vector((1,-3,4,2))
O= Matrix([w,x,y,z])
O

In [ ]:
Elim(O).TrC

T([(3, 2), (2, 1, 2), (3, 3), (-2, 1, 3), (3, 4), (-1, 1, 4), (-5, 2, 3), (-10, 2, 4), (7, 4), (-13, 3, 4)])

$\underset{\begin{subarray}{c} \left[\left(3\right)\mathbf{2}\right]\\\left[\left(2\right)\mathbf{1}+\mathbf{2} \right]\\\left[\left(3\right)\mathbf{3}\right]\\\left[\left(-2\right)\mathbf{1}+\mathbf{3} \right]\\\left[\left(3\right)\mathbf{4}\right]\\\left[\left(-1\right)\mathbf{1}+\mathbf{4} \right]\\\left[\left(-5\right)\mathbf{2}+\mathbf{3} \right]\\\left[\left(-10\right)\mathbf{2}+\mathbf{4} \right]\\\left[\left(7\right)\mathbf{4}\right]\\\left[\left(-13\right)\mathbf{3}+\mathbf{4} \right]\end{subarray}}{\pmb{\tau}}$

##Ejercicio 6

 6. Compara tus resultados del ejercicio 4 con el metodo ElimGJ()

In [ ]:
ElimGJ(N,1)

<IPython.core.display.Math object>

##Ejercicio 7

7. Encuentra la inversa de la matriz del ejercicio 1.

##Ejercicio 8

8. Resuelva el siguiente sistema de ecuaciones:

$$ \begin{array}{ccc}5x&+7y&-z&=6\\2x&+10y&-2z&=4\\x&+y&+z&=0\\ \end{array} $$